version: '3'
services:
  flask:
    build: .
    # command: gunicorn -w 4 -b 0.0.0.0:5000 hello:app --reload
    command: gunicorn -b 0.0.0.0:5000 hello:app --reload
    # command: gunicorn -b  91.76.199.83:5000 hello:app --reload
    environment:
       - FLASK_APP=hello.py
       - FLASK_DEBUG=1
       - PYTHONUNBUFFERED=True
    ports:
       - "5000:5000"
    volumes:
       - ./:/root
